apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: endo-api-data
  namespace: endo-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
