# pyproject.toml lint configuration addition
# Add this to your pyproject.toml to handle the local_settings import

# This file serves as a stub to satisfy linters when local_settings.py doesn't exist
# In luxnix deployments, this file is automatically generated with proper settings

# Development stubs - these would be overridden by real local_settings.py in production
DEBUG = None  # Will be overridden
SECRET_KEY = None  # Will be overridden
DATABASES = {}  # Will be overridden
ALLOWED_HOSTS = []  # Will be overridden

# This file is here purely to satisfy linting tools
# The actual local_settings.py is generated by luxnix deployment system
